# Site
repository: r-ballard/r-ballard.github.io #Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)
# Personal info
name: R. Ballard
title: Data Engineering and Analytics
email: russellcballard@gmail.com
#phone: Your phone number (optional)
cv   : "resume.pdf"
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
github_username:  r-ballard
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: russell-ballard-4b54064b
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced consultant with expertise in software engineering, enterprise analytics, and large-scale data projects.

  Interested in cloud and distributed computing architectures, generative art and design, and advanced analytics. 

  [Resume PDF](https://r-ballard.github.io/resume.pdf)

#Write an awesome description about yourself here, this supports markdown, so you can add links and highlight things **like this**.

#You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#- [My Awesome Resume](https://moya10.github.io/awesome-cv/resume.pdf)
#- Tables
#- Links
#- Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Scripting Languages:** Bash, Python, R, SQL
  
  **Libraries:**  boto, caret, gdal, geopandas, keras, nltk, numpy, pandas, scikit-learn, scipy

  **Data Warehouse Technologies:** Apache Sqoop, Cloudera, Hive, Impala Informatica, SQL Server, S3

  **Container/Environment:** AWS, Enterprise RedHat, Ubuntu, Windows

  **Visualization and BI:** Tableau, Excel VBA

  **Project Management and Version Control:** BitBucket, Jira, Git, GitHub, Kanban, MS Project, MS Teams

certifications_content: | #multiline section
  
  **Coursera**
  - [Practical Machine Learning - April 2018](https://r-ballard.github.io/certs/rballard_coursera_pml_0418.pdf)<br>
  - [Regression Models - April 2017](https://r-ballard.github.io/certs/rballard_coursera_regmod_0417.pdf)<br>
  - [Statistical Inference - February 2017](https://r-ballard.github.io/certs/rballard_coursera_statinf_0217.pdf)<br>
  - [Reproducible Research - November 2016](https://r-ballard.github.io/certs/rballard_coursera_repres_1116.pdf)<br>
  - [Exploratory Data Analysis - November 2016](https://r-ballard.github.io/certs/rballard_coursera_eda_1116.pdf)<br>
  - [Getting and Cleaning Data - October 2016](https://r-ballard.github.io/certs/rballard_coursera_getandclean_1016.pdf)<br>
  - [Data Scientist's Toolbox - August 2016](https://r-ballard.github.io/certs/rballard_coursera_dstb_0816.pdf)<br>
  - [R Programming - August 2016](https://r-ballard.github.io/certs/rballard_coursera_rprog_0816.pdf)<br>

  **DataCamp**
  - [Machine Learning Fundamentals Track](https://r-ballard.github.io/certs/rballard_dc_mlfpy_tr.pdf)
  - [Data Analyst with Python Track](https://r-ballard.github.io/certs/rballard_dc_dataanpy_tr.pdf)
  - [Data Manipulation with Python Track](https://r-ballard.github.io/certs/rballard_dc_datamanpy_tr.pdf)
  - [Data Scientist with Python Track](https://r-ballard.github.io/certs/rballard_dc_dspy_tr.pdf)
  - [Importing & Cleaning Data with Python Track](https://r-ballard.github.io/certs/rballard_dc_impclean_tr.pdf)
  - [Python Programmer Track](https://r-ballard.github.io/certs/rballard_dc_pyprog_tr.pdf)
  - [Case Study: School Budgeting with Machine Learning in Python - August 2017](https://r-ballard.github.io/certs/rballard_dc_csbudgetmlpy_0817.pdf)
  - [Introduction to Network Analysis in Python - October 2017](https://r-ballard.github.io/certs/rballard_dc_intnetan_1017.pdf)
  - [Introduction to Deep Learning in Python - October 2017](https://r-ballard.github.io/certs/rballard_dc_intdplrnpy_1017.pdf)
  - [Unsupervised Learning in Python - September 2017](https://r-ballard.github.io/certs/rballard_dc_unsuplrnpy_0917.pdf)
  - [Interactive Data Visualization with Bokeh - August 2017](https://r-ballard.github.io/certs/rballard_dc_intdatvisbok_0817.pdf)
  - [Supervised Learning with scikit-learn - August 2017](https://r-ballard.github.io/certs/rballard_dc_svlscikit_0817.pdf)
  - [Statistical Thinking in Python (Part 1) - July 2017](https://r-ballard.github.io/certs/rballard_dc_statthink1_0717.pdf)
  - [Statistical Thinking in Python (Part 2) - July 2017](https://r-ballard.github.io/certs/rballard_dc_statthink2_0717.pdf)
  - [Merging DataFrames with pandas - July 2017](https://r-ballard.github.io/certs/rballard_dc_mergepanda_0717.pdf)
  - [Manipulating DataFrames with pandas - July 2017](https://r-ballard.github.io/certs/rballard_dc_mandfpan_0617.pdf)
  - [pandas Foundations - June 2017](https://r-ballard.github.io/certs/rballard_dc_pandasfound_0617.pdf)
  - [Python Data Science Toolbox (Part 1) - June 2017](https://r-ballard.github.io/certs/rballard_dc_pydst1_0617.pdf)
  - [Python Data Science Toolbox (Part 2) - June 2017](https://r-ballard.github.io/certs/rballard_dc_pydst2_0617.pdf)
  - [Introduction to Databases in Python - June 2017](https://r-ballard.github.io/certs/rballard_dc_intdbpy_0617.pdf)
  - [Intermediate Importing Data in Python -  June 2017](https://r-ballard.github.io/certs/rballard_dc_intmimpdatpy_0717.pdf)
  - [Introduction to Data Visualization in Python - June 2017 ](https://r-ballard.github.io/certs/rballard_dc_datavizpy_0717.pdf)
  - [Cleaning Data in Python - June 2017](https://r-ballard.github.io/certs/rballard_dc_cleandatpy_0617.pdf)
  - [Introduction to Importing Data in Python - June 2017](https://r-ballard.github.io/certs/rballard_dc_impdatpy_0617.pdf)
  - [Intermediate Python - March 2017](https://r-ballard.github.io/certs/rballard_dc_intpy_0317.pdf)


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

relative_links:
  enabled:  true
  collections: true
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
